title: Habib Hotaki # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engineer | Researcher | Data | Statistics | Analysis | Design 
  <br><br>
  Research-oriented engineer with +10 years of combined experience 
  <br>
  in interdisciplinary engineering and data analysis in academia, 
  <br>
  public, and private sectors.
  <br><br>
  <img src="images/in1.png?raw=true"/><a href="https://www.linkedin.com/in/hotaki/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
